name: your_music
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  url_strategy: ^0.2.0
  readmore: ^2.2.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  file_picker: ^5.3.3
  firebase_storage: ^11.2.5
  firebase_storage_web: ^3.6.5
  just_audio: ^0.9.34
  firebase_messaging: ^14.6.5
  firebase_auth: ^4.7.2
  http: ^1.1.0
  sleek_circular_slider: ^2.0.1
  hive: ^2.2.3
  path_provider: ^2.1.0
  flutter_local_notifications: ^15.1.0+1
  just_audio_background: ^0.0.1-beta.10
  rxdart: ^0.27.7
  dartz: ^0.10.1
  googleapis_auth: ^1.4.1
  googleapis: ^11.4.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.10
  alan_voice: ^4.3.0
  fuzzywuzzy: ^1.1.6
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.1.0
  firebase_crashlytics: ^3.3.4
  firebase_remote_config: ^4.2.4
  firebase_analytics: ^10.4.4
  firebase_performance: ^0.9.2+4
  google_fonts: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: '#24283b'